name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest  # Use a Linux runner
    steps:
      - name: Checkout GitHub repository content
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Verify Node.js version
        run: node -v  # This step will print the Node.js version, useful for debugging

      - name: Install dependencies
        run: npm ci  # Use npm ci for a clean, reproducible install

      - name: Verify Node.js version before build
        run: node -v  # This step will print the Node.js version again, useful for ensuring the correct version is still set

      - name: Build the Next.js app
        run: npm run build

      - name: Verify Node.js version after build
        run: node -v  # This step will print the Node.js version again, useful for ensuring the correct version is still set

      - name: Set up Node.js for deployment
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Verify Node.js version before deploy
        run: node -v  # This step will print the Node.js version, useful for debugging

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: '/'  # Adjust this if your Next.js app is in a subdirectory
          output_location: '.next'  # The build output location for Next.js
          api_location: 'api'  # Set this to the location of your API or leave it empty if not applicable
